apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: owncloud
data:
  haproxy.cfg: |
    global
        log stdout format raw local0 info

    defaults
        mode http
        timeout client 10s
        timeout connect 5s
        timeout server 10s
        timeout http-request 10s
        log global

    frontend myfrontend
        bind *:8080
        default_backend owncloud_servers

    backend owncloud_servers
        balance roundrobin
        server oc1 owncloud-0.owncloud.owncloud.svc.cluster.local:80 check
        server oc2 owncloud-1.owncloud.owncloud.svc.cluster.local:80 check
