apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: owncloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:1.5.0
          env:
            - name: LDAP_ORGANISATION
              value: "OwnCloud Organization"
            - name: LDAP_DOMAIN
              value: "example.com"
            - name: LDAP_ADMIN_PASSWORD
              value: "adminpassword"
          ports:
            - containerPort: 389
            - containerPort: 636
          volumeMounts:
            - name: openldap-data
              mountPath: /var/lib/ldap
            - name: openldap-config
              mountPath: /etc/ldap/slapd.d
      volumes:
        - name: openldap-data
          persistentVolumeClaim:
            claimName: openldap-data-pvc
        - name: openldap-config
          persistentVolumeClaim:
            claimName: openldap-config-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: owncloud
spec:
  selector:
    app: openldap
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
    - protocol: TCP
      port: 636
      targetPort: 636
  type: ClusterIP
